[package]
name = "eint"
version = "0.1.0"
edition = "2021"
description = "Vectorization-friendly, fixed-size big integers."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
